import com.algosome.eutils.blast.Blast;
import com.algosome.eutils.blast.BlastParser;
import com.algosome.eutils.blast.GetCommand;
import com.algosome.eutils.blast.PutCommand;

public class BlastTest {
	public static void main(String[] args) {

		PutCommand put = new PutCommand();

		String searchThis = "TCAGTTGATTATGGCAAGAAGTCCAAGCTGGAGTTCTCCATTTACCCAGCACCCCAGGTTTCCACAGCTG"
				+ "TAGTTGAGCCCTACAACTCCATCCTCACCACCCACACCACCCTGGAGCACTCTGATTGTGCCTTCATGGTAGACAATGAG"
				+ "GCCATCTATGACATCTGTCGTAGAAACCTCGATATCGAGCGCCCAACCTACACTAACCTTAACCGCCTTATTAGCCAGAT"
				+ "TGTGTCCTCCATCACTGCTTCCCTGAGATTTGATGGAGCCCTGAATGTTGACCTGACAGAATTCCAGACCAACCTGGTGC"
				+ "CCTACCCCCGCATCCACTTCCCTCTGGCCACATATGCCCCTGTCATCTCTGCTGAGAAAGCCTACCATGAACAGCTTTCT"
				+ "GTAGCAGAGATCACCAATGCTTGCTTTGAGCCAGCCAACCAGATGGTGAAATGTGACCCTCGCCATGGTAAATACATGGC"
				+ "TGTGTGTGTGTCGGTGCACATGCTTTACATGTGTTTAGTCGAGGTTAAAAAAACGTCTAGGCCCCCCGAACCACGGGGAC"
				+ "GTGGTTTTCCTTTGAAAAACACGATGATAAGCTTGCCACAACCCACAAGGAGACGACCTTCCATGACCGAGTACAAGCCC"
				+ "ACGGTGCGCCTCGCCACCCGCGACGACGTCCCCCGGGCCGTACGCACCCTCGCCGCCGCGTTCGCCGACTACCCCGCCAC"
				+ "GCGCCACACCGTCGACCCGGACCGCCACATCGAGCGGGTCACCGAGCTGCAAGAACTCTTCCTCACGCGCGTCGGGCTCG"
				+ "ACATCGGCAAGGTGTGGGTCGCGGACGACGGCGCCGCGGTGGCGGTCTGGACCACGCCGGAGAGCGTCGAAGCGGGGGCG"
				+ "GTGTTCGCCGAGATCGGCCCGCGCATGGCCGAGTTGAGCGGTTCCCGGCTGGCCGCGCAGCAACAGATGGAAGGCCTCCT"
				+ "GGCGCCGCACCGGCCCAAGGAGCCCGCGTGGTTCCTGGCCACCGTCGGCGTCTCGCCCGACCACCAGGGCAAGGGTCTGG"
				+ "GCAGCGCCGTCGTGCTCCCCGGAGTGGAGGCGGCCGAGCGCGCCGGGGTGCCCGCCTTCCTGGAGACCTCCGCGCCCCGC"
				+ "AACCTCCCCTTCTACGAGCGGCTCGGCTTCACCGTCACCGCCGACGTCGAGTGCCCGAAGGACCGCGCGACCTGGTGCAT"
				+ "GACCCGCAAGCCCGGTGCCTGACGCCCGCCCCACGACCCGC";

		put.setQuery(searchThis);

		put.setProgram("blastp");
		put.setDatabase("nr");

		//Construct a GetCommand to get the results
		GetCommand get = new GetCommand(new BlastParser(){
			@Override

			/**
			 * Simply prints results to the command line
			 * @param output The output from the blast results.
			 */

			public void parseBlastOutput(String output) {

				System.out.println(output);

			}
		});

		get.setFormatType("Text");

		//Create the Blast object to run the get and put processes
		Blast blast = new Blast(put, get);

		//Run the alignment. Blast implements Runnable, and can therefore be run in a separate thread.
		blast.run();
	}
}
